name: CI/CD on PR

on:
  pull_request:
    types:
      - created

jobs:
  cd-dev:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: ws-room-service
      docker-tag: ${{ GITHUB_SHA }}
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
